version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
