include: package:lints/recommended.yaml

analyzer:
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error
    todo: ignore
  exclude:
   - lib/src/third_party/**

linter:
  rules:
    - avoid_catching_errors
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_returning_null_for_future
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - directives_ordering
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_runtimeType_toString
    - only_throw_errors
    - package_api_docs
    - prefer_asserts_in_initializer_lists
    - prefer_const_declarations
    - prefer_relative_imports
    - prefer_single_quotes
    - sort_pub_dependencies
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_parenthesis
    - unnecessary_statements
