include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
   - lib/src/third_party/**

  language:
    strict-casts: true
    strict-inference: true

linter:
  rules:
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - missing_code_block_language_in_doc_comment
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_runtimeType_toString
    - package_api_docs
    - prefer_const_declarations
    - prefer_final_locals
    - require_trailing_commas
    - unawaited_futures
    - unreachable_from_main
    - use_enums
