include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error
    todo: ignore

linter:
  rules:
    - avoid_function_literals_in_foreach_calls
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_future
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - control_flow_in_finally
    - directives_ordering
    - empty_statements
    - implementation_imports
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - non_constant_identifier_names
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_initializing_formals
    - prefer_typing_uninitialized_variables
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_parenthesis
    - unnecessary_statements
