name: Sync version tags from SDK
on:
  schedule:
    # Run every day at 00:00
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  tag_from_sdk:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        fetch-depth: 0 # Check out everything to be able to tag.
        persist-credentials: false
    - uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d
      with:
        sdk: stable
    - id: install
      name: Install dependencies
      run: dart pub get
    - id: tags
      name: push_missing_tags_to_origin
      run: dart tool/create_version_tags_from_sdk.dart --create --push
